### ISSUE TITLE
husky & typo error

### ISSUE THREAD

**Issue by shadirahdari** [shadirahdari/eshop#1]
@sashkakorkh 
I pulled the main branch, there was typo error which I fixed 
https://github.com/shadirahdari/eshop/commit/71e0d0bf73f189d16dbd08d58a1a302559a00be3

also Husky was preventing me to push codes so I disabled that too
https://github.com/shadirahdari/eshop/commit/488c9eb35c84cda1849826564e88da4d1ec163d7

I committed my works [here ](https://github.com/shadirahdari/eshop/commit/f317d0acde7d2932869f409f341a68458a702b6f).  may you please put that inside src & make it work?

Thanks

**Comment by sashkakorkh** [comment]
Issues have been solved
